# Use postgres/example user/password credentials
#docker-compose -f D:\spring\spring-examples\spring-datajpa-postgresql\src\main\resources\docker-compose.yml up -d
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: 123123

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080